package cn.edu.upc.csn.dao;

import cn.edu.upc.csn.model.Csnuser;

import java.util.List;

public interface CsnuserMapper {
    List<Csnuser> denglu(Csnuser record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csnuser
     *
     * @mbg.generated Sun Aug 23 17:02:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csnuser
     *
     * @mbg.generated Sun Aug 23 17:02:59 CST 2020
     */
    int insert(Csnuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csnuser
     *
     * @mbg.generated Sun Aug 23 17:02:59 CST 2020
     */
    int insertSelective(Csnuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csnuser
     *
     * @mbg.generated Sun Aug 23 17:02:59 CST 2020
     */
    Csnuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csnuser
     *
     * @mbg.generated Sun Aug 23 17:02:59 CST 2020
     */
    int updateByPrimaryKeySelective(Csnuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csnuser
     *
     * @mbg.generated Sun Aug 23 17:02:59 CST 2020
     */
    int updateByPrimaryKey(Csnuser record);
}